### ISSUE TITLE
Does not work with Java 8 and Spring Boot 1.4.x

### ISSUE THREAD

**Issue by gregorycfrank** [JadiraOrg/jadira#61]
With validation on my app crashes at startup. Given the code

    @Column
    @Type(type = "org.jadira.usertype.moneyandcurrency.joda.PersistentMoneyAmount",
            parameters = {@org.hibernate.annotations.Parameter(name = "currencyCode", value = "USD")})
    private Money requiredAmount;

I get a stack trace

    Caused by: java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionFactoryImplementor.getProperties()Ljava/util/Map;
	at org.jadira.usertype.spi.shared.AbstractUserTypeHibernateIntegrator.integrate(AbstractUserTypeHibernateIntegrator.java:192) ~[usertype.spi-6.0.1.GA.jar:?]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:280) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]

**Comment by chrisphe** [comment]
The relevant method was removed from SessionFactoryImplementor because it is in the supertype, EntityManagerFactory as of JPA 2. You need to use the right JPA jar or revert to an earlier version of Hibernate. See https://stackoverflow.com/questions/38511184/spring-4-3-1-hibernate-5-2-1-creating-sessionfactoryimplementor-getproperties
